document.type.*:
  type: config_entity
  label: 'Document type'
  mapping:
    id:
      type: machine_name
      label: 'Machine name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
    review:
      type: mapping
      label: 'Review policy'
      mapping:
        instructions:
          type: text
          label: 'Review instructions'
        options:
          type: sequence
          label: 'Decisions'
          sequence:
            type: label
            label: 'Decision label'
